### ISSUE TITLE
Short example of a reverse-solvable Wordle

### ISSUE THREAD

**Issue by ArchRobison** [davidebbo/WordleReverseSolver#2]
For test purposes and amusement, the example here might be interesting: [](https://www.blonzonics.us/miscellaneous/wordle-solvable-from-colors-only) . It's reverse-solvable from a single board.

**Comment by davidebbo** [comment]
@ArchRobison That sounds interesting. Did you mean to include a link? It's not showing up for me.

**Comment by ArchRobison** [comment]
I forgot the link.  https://www.blonzonics.us/miscellaneous/wordle-solvable-from-colors-only

**Comment by davidebbo** [comment]
Thanks, I will take a look later today, that seems quite interesting. Also, I've never looked at Julia code before :)

**Comment by davidebbo** [comment]
Interesting approach, and definitely different from what I did. The heuristic to decide what next guess to use is clever. My logic is mostly brute force.

One thing worth mentioning: in my case, I chose not to use the knowledge that only a subset of the words can be answers, because I felt this was knowledge I was not supposed to have. i.e. we only know this from the source code, which really should have been hidden from us. That makes it harder to find a solution, since now we have ~13k possible answers. You could easily tweak your solution to see how it fares with that larger answer space.

**Comment by ArchRobison** [comment]
I tried my puzzle constructor (not on the site) with the set of answers set to the full 12972 set of words.  It came up with a seven-guess puzzle:
```
      12972
gyggy 852
yggyg 113
ggygy 26
gygyy 9
gbggy 3
ybggb 1
```
The letters denote green/yellow/black. The numbers denote the number of remaining possible answers. An additional 7th guess after the six shown is required to get all-green.

The puzzle constructor is a greedy algorithm that chooses the response that most shrinks the answer set. It's not doing any look-head, so it's possible that shorter puzzles exist.

**Comment by davidebbo** [comment]
Very nice. Which specific answer was that for?

For me, the biggest challenge was dealing with 'dirty' tweets. i.e. tweets that has patterns that cannot exist for the current day's puzzle. Typically, this is caused by tweets related to different Wordle languages that cannot easily be filtered out. I ended up going with a best fit approach, with the assumption that English tweets would outnumber unwanted ones. But that was far from perfect.

Side note: on [here](https://www.blonzonics.us/miscellaneous/wordle-solvable-from-colors-only), you have one of the game responses as "gyggg", which doesn't seem right. i.e. you can't have 4 correct letters and 1 misplaced letter. Right?

**Comment by ArchRobison** [comment]
Best fit sounds like a good solution.  I noticed the wrong-tweet problem but didn't come up with a solution.

Your question about `gyggg` is good. It looks like I misinterpreted the rules. I was assuming `y` meant "guess letter appears in answer", but according to https://nerdschalk.com/wordle-same-letter-twice-rules-explained-how-does-it-work/ Wordle is stricter about such matters.  I'll verify that is indeed the case and update my code.

**Comment by ArchRobison** [comment]
I updated the example at https://www.blonzonics.us/miscellaneous/wordle-solvable-from-colors-only .  Fixing the double-letter bug yields slightly more information and the new example (answer is "torus") takes only 3 guesses.

 With the big answer space, there is a 4 guess board with a unique solution. As before, the numbers denote the number of remaining possible answers:
 ```
       12972
gyygy 124
ygggy 2
yggbb 1
["sotol"]
```

**Comment by davidebbo** [comment]
Very nice! If I had more time, I would try to set up Julia and play with your code. But realistically, I probably won't :)

**Comment by ArchRobison** [comment]
Thanks for pointing out my double-letter bug.  I'll close the issue.
